### ISSUE TITLE
Allow override of `build_profile` setting per-package.

### ISSUE THREAD

**Issue by ccollins476ad** [apache/mynewt-newt#153]
E.g., if the user wants to debug a the "nimble/host" package on constrained hardware, they might do the following:

1. Set `target.build_profile` to `optimized`.
2. In `net/nimble/host/pkg.yml`, set `pkg.build_profile` to `debug`.

Currently, there is no way to override the build profile in an individual package.

**Comment by sterlinghughes** [comment]
Would another solution to be allowing libraries to be targets?  I'm not sure I'd like to have this at the package level, as I think it becomes very confusing when optimization level is overwritten by a library within the build system.  I'd prefer a way of making this explicit at the target level.

**Comment by utzig** [comment]
Wouldn't it be possible to override `build_profile` for some packages, like:

```
target.app: "apps/slinky"
target.bsp: "hw/bsp/stm32f3discovery"
target.build_profile: optimized
target.build_profile.pkg_override.debug:
  - "net/nimble"
  - "sys/console/full"
```

Just a suggestion of syntax to make an example...

**Comment by ccollins476ad** [comment]
I agree - it is better if this is specified in the target.   Thanks for preventing bad idea from being implemented :).

**Comment by andrzej-kaczmarek** [comment]
I agree target is the proper place for user to override build profile, however I think it would be also good to have this in package (as per initial proposal). For example, `sys/sysview` package should be always built optimized since we want this code to execute quickly and it's unlikely someone will actually debug it. Of course, it can be then overridden in target if needed.

Note that it is not possible to simply build `sys/sysview` with `pkg.cflags` set to e.g. `-O2` since `newt` sorts all flags and with debug build profile we'll have `-O2 -Og` which effectively selects `-Og`.
